#!/bin/bash

# sudo su
# apt-get install mailutils

if [ !/root/checksum_file ]
then
	md5sum /etc/crontab > /root/checksum_file
fi

echo "#md5sum -c /root/checksum_file
#!/bin/sh

MD5SUM='cat /root/checksum_file'
MD5NEW='md5sum /etc/crontab'

if [ "$MD5SUM" != "$MD5NEW" ]
then
	echo "/etc/crontab has been modified.." | mail -s "alert" root
fi" > /etc/cron.daily/04
chmod 755 /etc/cron.daily/04

# crontab -e 0 0 * * * /etc/cron.daily/04
